name: ubuntu

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md', 'docs/**' ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: A job to build and run strfry on Ubuntu
    steps:
      - name: Checkout strfry
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build strfry
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends \
          build-essential git g++ make pkg-config libtool ca-certificates \
          libssl-dev zlib1g-dev liblmdb-dev libflatbuffers-dev libsecp256k1-dev libzstd-dev
          git submodule update --init
          make setup-golpe
          make -j$(nproc)
          if ! [ -f ./strfry ]; then
             echo "Strfry build failed."
             exit 1
          fi

      - name: Run strfry (With Crash Check)
        run: |
          cat /etc/os-release
          ./strfry --set relay__nofiles=65536 relay > log 2>&1 &
          sleep 2
          pgrep -f strfry || (cat log && exit 1)
          pkill -f strfry

